[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atlasynq-shared-types"
version = "0.1.0"
description = "Shared schemas for AtlaSynq"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["shared_types*"]
